config/routes.rb
Rails.application.routes.draw do
  resources :articles
  
 

get 'articles/new'

   root to: 'articles#index'

  

end

app/models/article.rb
class Article < ActiveRecord::Base
    
    validates :title, presence: true
    validates :body, presence: true
    
    #default_scope{ order(created_at: :desc)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
before_action :set_article, only: [:show, :edit, :update, :destroy]
  def index
      @articles = Article.all.order('created_at DESC')
  end
  
  def new
  	@article = Article.new
  end

  def create
  	@article = Article.new(article_params)
  	if @article.save 
        flash[:success] = "Article created successfully"
  	   redirect_to root_path
  	   
  	   else
        flash.now[:danger] = "article was not created"
  	   render 'new'
     end	
  end

  def show
    
end

  def edit
   
  end

  def update
     
    if @article.update(article_params)

      redirect_to @article, notice: 'Article was successfully updated.'

    else

      render 'edit'
    end
  end

def destroy
  

  if @article.destroy
  redirect_to articles_url, notice: 'Article was successfully destroyed.'

end
end

private

def set_article
@article = Article.find(params[:id])
  end

  def article_params
  	params.require(:article).permit(:title, :body)
 end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def bootstrap_class_for flash_type
    case flash_type
      when :success
        "alert-success"
      when :error
        "alert-error"
      when :alert
        "alert-block"
      when :notice
        "alert-info"
      else
        flash_type.to_s
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<div class="row">
	<div class="col-md-12">

<%= form_for(@article, :html => { class: "form-horizontal", role: "form" }) do |f| %>

<% if @article.errors.any? %>
    <div id="error_explanation alert alert-danger alert-dismissible" role="alert">
         <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4><%= pluralize(@article.errors.count, "error") %> prohibited this listing from being saved:</h4>

      <ul>
          <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group">
	<div class="control-label col-md-1">
<%= f.label :title %>
</div>
<div class="col-md-11">
<%= f.text_field :title, class: "form-control", placeholder: "Title of Article here", autofocus: true %>
</div>
</div>


<div class="form-group">
	<div class="control-label col-md-1">
<%= f.label :body %>
</div>
<div class="col-md-11">
<%= f.text_area :body, row: 10, class: "form-control", placeholder: "Content of your article here" %>
</div>
</div>


     <div class="control-label col-md-1">
     <div class="form-group">
     	<%= f.submit "Submit", class: "btn btn-primary btn-lg pull-right" %> 
     </div>
     </div>

<% end %>
</div>
</div>

app/views/articles/edit.html.erb
<h2 class="text-center">Edit your Article here</h2>

<%= render 'form' %>

<%= link_to 'Homepage', root_path, class: "btn btn-link" %>

app/views/articles/index.html.erb
<h3>List all Articles</h3>

<%= link_to 'New Article', new_article_path, class: "btn btn-success btn-lg", id: "new-article-btn" %>

<% @articles.each do |article| %>
<div class="well well-lg">
<div class="article-title">
    <h3><%= link_to article.title , article_path(article) %></h3>
    </div>
    <div class="article-body">
<p><%= truncate(article.body, length: 200) %></p>
    </div>

</div>
<% end %>

app/views/articles/new.html.erb
<h1 class="text-center">New Article</h1>

<%= render 'form' %>

<%= link_to 'Back to HomePage', root_path %>

app/views/articles/show.html.erb
<h3><%= @article.title  %></h3>
<p><%= @article.body %></p>

<br>

<p><%= link_to 'Edit', edit_article_path(@article) %> |
</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Staff Manager', root_path, class: "navbar-brand", id: "logo" %>
      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Articles <span class="sr-only">(current)</span></a></li>
       
        <li> <%= link_to 'Home', root_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Account <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StaffManager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render '/layouts/navbar' %>

<div class="container-fluid">
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>


	<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<div class="col-md-8">
	<%= yield %>
</div>

<div class="col-md-4">
	<%= yield :sidebar %> 
</div>
</div>
</div>
</div>

</body>
</html>